const checkFunction = () => {
    try {
        console.log("check Function");        
    } catch (error) {
        console.error(error);
    }
}
checkFunctin();//recheck